In [16]:
import numpy as np
import pandas as pd
df = pd.read_csv('hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [3]:
df.isna().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [4]:
df.experience.isna()

0     True
1     True
2    False
3    False
4    False
5    False
6    False
7    False
Name: experience, dtype: bool

In [18]:
df.experience = df.experience.fillna('zero')
df.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
df['test_score(out of 10)'].isna().sum()

1

In [12]:
import math
test_score_median = math.floor(df['test_score(out of 10)'].median())
test_score_median

8

In [17]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(test_score_median)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [32]:
import word2number
from word2number import w2n


df.experience = df.experience.apply(lambda x : w2n.word_to_num(x))
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [36]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df[['salary($)']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [37]:
lr_model.coef_

array([[2812.95487627, 1845.70596798, 2205.24017467]])

In [38]:
lr_model.intercept_

array([17737.26346434])

In [39]:
lr_model.predict([[2,9,6]])

array([[53205.96797671]])

In [40]:
2812.95487627*2 + 1845.70596798*9 + 2205.24017467*6 + 17737.26346434

53205.96797672001

In [41]:
lr_model.predict([[12,10,10]])

array([[92002.18340611]])